### ISSUE TITLE
raw_search_title doesn't always give good results

### ISSUE THREAD

**Issue by ronan-mch** [team-umlaut/umlaut#32]
Leaving this as a placeholder for myself. For some Open URLs, raw_search_title returns blank, despite there being a useful title in the metadata hash. e.g. resolve?ctx_ver=Z39.88-2004&ctx_enc=info:ofi/enc:UTF-8&ctx_tim=2013-11-25T10%3A59%3A44IST&url_ver=Z39.88-2004&url_ctx_fmt=infofi/fmt:kev:mtx:ctx&rfr_id=info:sid/primo.exlibrisgroup.com:primo3-Article-sciversesciencedirect_elsevier&rft_val_fmt=info:ofi/fmt:kev:mtx:&rft.genre=article&rft.atitle=Supercritical water gasification of biomass: Thermodynamic constraints&rft.jtitle=Bioresource Technology&rft.btitle=&rft.aulast=Castello&rft.auinit=&rft.auinit1=&rft.auinitm=&rft.ausuffix=&rft.au=Castello%2C Daniele&rft.aucorp=&rft.date=2011&rft.volume=102&rft.issue=16&rft.part=&rft.quarter=&rft.ssn=&rft.spage=7574&rft.epage=7582&rft.pages=7574-7582&rft.artnum=&rft.issn=0960-8524&rft.eissn=&rft.isbn=&rft.sici=&rft.coden=&rft_id=info:doi/10.1016/j.biortech.2011.05.017&rft_dat=<sciversesciencedirect_elsevier>S0960-8524(11)00656-0</sciversesciencedirect_elsevier>&rft.eisbn=&rft_id=info:oai/

returns blank. This seems to be something to do with the boolean tests on the blank strings. It can be solved by changing these to include length tests, but perhaps there is a better way to fix this in the metadata helper?

**Comment by jrochkind** [comment]
raw_search_title is designed to get 'container' title, journal, not article. 

But in current Umlaut 4.1, it seems to correctly return the journal title "Bioresource Technology" for your example citation. I think whatever was broken is fixed.
